name: Terraform Apply

on:
  push:
    branches: ["main"]          # Runs automatically on push to main
  workflow_dispatch:             # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:               # <-- OIDC permissions
      id-token: write           # GitHub can request OIDC token
      contents: read            # Workflow can read repo files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::269809345657:role/github-actions-terraform
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check S3 backend exists
        run: |
          if ! aws s3 ls s3://maya-terraform-state-123456 >/dev/null 2>&1; then
            echo "Backend S3 bucket does not exist! Run bootstrap workflow first."
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ./terraform


      - name: Build Docker Image (no cache)
        run: |
          echo "Building Docker image with latest tag"
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/java-devops-app:latest .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-devops-app:latest

      - name: Tag and Push latest for Watchtower
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/java-devops-app:${GITHUB_SHA} ${{ secrets.DOCKERHUB_USERNAME }}/java-devops-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-devops-app:latest


      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="aws_region=eu-central-1" \
            -var="docker_image=${{ secrets.DOCKERHUB_USERNAME }}/java-devops-app:latest" \
            -var="docker_username=${{ secrets.DOCKERHUB_USERNAME }}" \
            -var="docker_token=${{ secrets.DOCKERHUB_TOKEN }}"
        working-directory: ./terraform  
